name: Generate GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * 0" }] # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_languages: yes
          plugin_languages_ignored: html, css, cython
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: true
